### ISSUE TITLE
Blockstack issue tracker

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#5]
There are a few issues with the Blockstack integration:

- [x] https://github.com/blockstack/blockstack-core/issues/499
- [x] https://github.com/blockstack/blockstack.js/issues/236
- [ ] https://github.com/blockstack/blockstack.js/issues/264 & https://github.com/blockstack/blockstack.js/issues/531
- [x] https://github.com/blockstack/blockstack-browser/issues/631

And I'm also waiting on some updates in order to integrate Gaia (Blockstack's storage system) as a `Source`:

- [x] https://github.com/blockstack/blockstack-core/issues/500

**Comment by icidasset** [comment]
Issue nr. 1 is fixed with browser version `0.12.0`.

**Comment by icidasset** [comment]
Issue nr. 2 is fixed with the latest Blockstack.js

**Comment by icidasset** [comment]
Workaround for the web-worker issue, use this function directly: https://github.com/blockstack/blockstack.js/blob/77765a13372b3ddb39c8c2a12b3defd6afa7163d/src/storage/hub.js#L93
